export const location = [
  "Northland",
  "Auckland",
  "Waikato",
  "Rotorua",
  "Taupo",
  "Taranaki",
  "Whanganui",
  "Manawatu",
  "The Coromandel",
  "Bay of Plenty",
  "Tairawhiti",
  "Ruapehu",
  "Hawke's Bay",
  "Wairarapa",
  "Wellington",
  "Nelson Tasman",
  "West Coast",
  "Wanaka",
  "Queenstown",
  "Fiordland",
  "Southland",
  "Marlborough",
  "Christchruch",
  "Waitaki",
  "Centeral Otago",
  "Dunedin",
  "Clutha",
];

export const links = [
  "northland",
  "auckland",
  "waikato",
  "rotorua",
  "taupo",
  "taranaki",
  "whanganui",
  "manawatu",
  "coromandel",
  "bay-of-plenty",
  "tairawhiti",
  "ruapehu",
  "hawkes-bay",
  "wairarapa",
  "wellington",
  "nelson-tasman",
  "west-coast",
  "lake-wanaka",
  "queenstown",
  "fiordland",
  "southland",
  "marlborough",
  "christchurch-canterbury",
  "waitaki",
  "central-otago",
  "dunedin-coastal-otago",
  "clutha",
];

export const header = [
  "Poor Knights Islands",
  "Viaduct Harbour",
  "Whale Bay, Raglan",
  "Whakarewarewa Forest",
  "Huka Falls",
  "Egmont National Park",
  "Whanganui River",
  "Exploring the gorge",
  "Cathedral Cove",
  "Bay of Plenty",
  "Mount Hikurangi",
  "Tongariro Alpine Crossing",
  "Craggy Range Winery",
  "Castlepoint",
  "Wellington City",
  "Abel Tasman",
  "Blue Pools, Wanaka",
  "Kayak Lake Wanaka",
  "The Remarkables",
  "Milford Sound",
  "Waipapa Point",
  "Marlborough Sounds",
  "Hanmer Springs",
  "Moeraki Boulders",
  "Lake Dunstan Entrance",
  "Larnach Castle",
  "Tautuku Bay",
];

export const footer = [
  "By Alistair Guthrie",
  "By ATEED",
  "By Graeme Murray",
  "By Destination Rotorua",
  "By Graeme Murray",
  "By Titine",
  "By Tourism New Zealand",
  "By ManawatuNZ",
  "By Adam Bryce",
  "By Chris McLennan",
  "By Matt Crawford",
  "By Visit Ruapehu",
  "By FAWC",
  "By Mike Heydon",
  "By Graeme Murray",
  "By Fraser Clements",
  "By Fraser Clements",
  "By Miles Holden",
  "By Miles Holden",
  "By Alistair Guthrie",
  "By Venture Southland",
  "By Destination Marlborough",
  "By Matt Crawford",
  "By Miles Holden",
  "By Heritage Lake Resort",
  "By Dunedin NZ",
  "By Blacklabel Photography",
];

export const imageLinks = [
  "https://www.newzealand.com/assets/Tourism-NZ/Northland-Bay-of-Islands/9bafd18f11/img-1536260527-838-24889-7819F476-E8A5-E743-CC8F9C60EB05B368__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Auckland/Viaduct-Harbour-Central-Auckland-1__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Hamilton-Waikato/4ada9be239/img-1536906834-7627-32566-p-B8C424EA-EBB8-D2DE-DC0C677FB518489D-2544003__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDYwLDMyLDc1LCJqcGciLDY1LDIuNV0.JPG",
  "https://www.newzealand.com/assets/Tourism-NZ/Rotorua/20f456204e/img-1536084229-7842-25351-p-2F8A6F4D-A32A-AC1D-738D769122D2296E-2544003__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Lake-Taupo/6030dffce0/img-1536370495-280-18355-E360B861-C791-F81C-E751CF8973B0F707__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Taranaki/fe080b172f/img-1536038499-4706-32459-p-A1EEE5A2-9F5D-3937-7552E30567443DEE-2544003__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQ5LDQxLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Whanganui/143b3c9ae1/img-1536252532-4279-20135-969D3C69-B8FE-A7CB-13EA00B93267F23C__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQxLDYwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Manawatu/d3ca3e5620/img-1536132571-3973-16741-p-D5AA8CC7-EC87-50B5-EB61A6F0EF9D648F-2544003__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDMwLDUwLDc1LCJwbmciLDY1LDIuNV0.png",
  "https://www.newzealand.com/assets/Tourism-NZ/The-Coromandel/a693605527/img-1536199879-5892-32422-DB127D95-90CD-AC3E-A7B6DB13E22BD7B8__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDY4LDU5LDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Bay-of-Plenty/abd1fa3b1d/img-1536060969-2877-15004-p-C6CD9BD9-F5AC-4AF9-8B80C1877F9EDDA1-2544003__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJwbmciLDY1LDIuNV0.png",
  "https://www.newzealand.com/assets/Campaigns/FY-20-Campaigns/FY20-Brand-Welcome/GMW-Still-Assets/Job1689_Tnz_Hikurangi2_Mc_0859_Final_HR__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Other/8c345a5b90/img-1536366257-2883-13131-977A8D96-BF36-79D6-5C0F75563DEC6C2B__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQ0LDYzLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Hawkes-Bay/bd9365b9e9/img-1536328411-3176-11253-2A2588F3-94BB-407A-3480E0084C1E59E0__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQxLDYxLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Wairarapa/e84230c80b/img-1536208132-1096-3076-513D2F56-CF17-C1F3-C30476F77B672ECA__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQ5LDQ0LDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Campaigns/FY-20-Campaigns/FY20-Brand-Welcome/GMW-Still-Assets/121-Wellington-City-Graeme-Murray__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Nelson/EX22181_Abel_Tasman_Fraser_Clements__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDU0LDU5LDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/West-Coast/87dd626eab/img-1536343152-4203-9973-CB3A04D4-04FE-AF7C-5D83D06C3711E00B__aWxvdmVrZWxseQo_FocalPointCropWzExMDAsMzIwMCw1MCw1MCw3NSwianBnIiw2NSwyLjVd.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Wanaka/0f9369f9ec/img-1536326604-7780-3379-FD6812F8-F948-F438-FBFC8ECE30ACDEDB__aWxvdmVrZWxseQo_FocalPointCropWzExMDAsMzIwMCw0NCw1NCw3NSwianBnIiw2NSwyLjVd.jpg",
  "https://www.newzealand.com/assets/Campaigns/FY-20-Campaigns/FY20-Brand-Welcome/GMW-Still-Assets/1830-The-Remarkables-Queenstown-Miles-Holden__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQ5LDQ3LDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Fiordland/342a08eaf0/img-1536236924-3819-10834-E1D317D1-92AB-5BFA-44C8BEA121131507__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDYxLDUyLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Southland/9520348a5d/img-1536309252-237-7175-B1AD9482-0339-D540-509C02F0C74A452A__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQ1LDY4LDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Marlborough/bde3e21c48/img-1536376197-9507-10747-65BF405A-C9B9-190D-7A6610D101730871__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Campaigns/FY-20-Campaigns/FY20-Brand-Welcome/GMW-Still-Assets/1111-Hanmer-Springs-Canterbury-Matt-Crawford__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUxLDY0LDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Waitaki/bd5cf3eca2/img-1536200396-4422-2074-5DDB8C2F-B84C-CC3D-568B5BA0D6F32A5E__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Other/8f57227c84/img-1568376214-1991-26435-p-9731798C-D8BA-6EE1-6D0B37C3E3BDB8AF-2544003__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDQ2LDU1LDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Operator-Database/img-1598584699-4860-6384-attractions_larnachcastle_097_dunedinnz__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDUwLDc1LCJqcGciLDY1LDIuNV0.jpg",
  "https://www.newzealand.com/assets/Tourism-NZ/Clutha/67faae3e10/img-1542383606-6354-25539-604586BC-DCD5-57A4-B339D6C7079CAA22__aWxvdmVrZWxseQo_FocalPointCropWzY2MCwxOTIwLDUwLDM0LDc1LCJqcGciLDY1LDIuNV0.jpg",
];

export const info = [
  "The subtropical Northland region of New Zealand stretches upwards from Auckland to the very top of New Zealand. Take a journey along the Twin Coast Discovery Highway to the iconic Bay of Islands, as well as the Kauri Coast, the Far North, and Whangarei.",
  "Tāmaki Makaurau Auckland is an urban oasis. It’s where sparkling waters and lush landscapes meet city sophistication.",
  "Just south of Auckland lies the Waikato region; a land of lush pastures that was chosen to play The Shire in The Lord of the Rings and The Hobbit films.",
  "Rotorua is known for bubbling mud pools, shooting geysers and natural hot springs, as well as showcasing our fascinating Māori culture.",
  "From adrenaline-pumping activities to ancient forests to relaxing hot springs, the heart of the North Island offers something for everyone.",
  "From world-class surf breaks to a perfectly formed volcanic peak, Taranaki offers countless opportunities for adventure.",
  "Whanganui was one of the first cities to be founded in New Zealand. Whanganui, meaning 'big bay' or 'big harbour', comes from the great river that flows through it.",
  "Located in the lower North Island, Manawatū is heartland New Zealand, offering an authentic Kiwi experience that's not to be missed.",
  "The Coromandel, renowned for its pristine beaches, misty forests and laid-back vibe, is one of New Zealand's most popular holiday destinations.",
  "The Bay of Plenty region is home to spectacular beaches, juicy kiwifruit and geothermal wonders.",
  "Tairawhiti is the place where the first Polynesian canoes landed, James Cook made his first landfall and Maori and European first encountered each other.",
  "In the heart of the North Island, Ruapehu’s two national parks and surrounding countryside provide a beautiful backdrop to many outdoor adventures.",
  "There are two words that best describe Hawke's Bay and they are Wine Country - but there is much more than wine to this sunny region.",
  "Wairarapa is an hour's drive north of Wellington. Visit the vineyards of Martinborough or Cape Palliser, the southernmost point of the North Island.",
  'Situated at the southern end of the North Island, Wellington, New Zealand, was recently named "the coolest little capital in the world" by Lonely Planet.',
  "Nelson Tasman is an extraordinary, vibrant region where art and businesses thrive together among a stunning natural landscape.",
  "The West Coast, or 'the Coast' as locals call it, is an untamed natural wilderness of rivers and rainforests, glaciers and geological treasures.",
  "At 45 kilometres long and covering 193 square kilometres, Lake Wanaka is perfect for jetboaters, sailors and kayakers to explore.",
  "Queenstown is one of New Zealand’s most exciting destinations. Surrounded by towering mountains, positioned on the edge of a lake, Queenstown is a hub of adventure, thrumming with adrenaline and an omnipresent sense of fun.",
  "Fiordland is one of the most dramatic and beautiful parts of New Zealand. Absorb the breathtaking treasures of this region by water, air or hiking.",
  "Southland is a land of rugged coast and rolling plains, world-renowned Bluff oysters and the launching place for a visit to Stewart Island.",
  "The Marlborough region is about world-famous Sauvignon Blanc, delicious fresh seafood and diverse landscapes, from valleys of vines to sheltered waterways.",
  "Set against the majestic backdrops of both alps and ocean, there is so much to discover in Christchurch and Canterbury.",
  "The Waitaki region is a place of scenic contrast and haunting natural beauty. Experience mysterious boulders, windswept beaches and Maori rock art.",
  "Central Otago is a powerful landscape, sunny, dry and brown with weathered ancient mountains, alpine herb fields and fast flowing rivers. ",
  "Dunedin is a region of unique landscapes and fascinating cultural history. Enjoy getting close to rare wildlife and soaking up the quirky city vibe.",
  "Unique and unspoiled, Clutha has amazing wildlife, wonderful waterfalls, beautiful beaches along with a rich gold mining heritage.",
];
